author: Doug
author_url: https://github.com/dougzilla32
module: CPKAlamofire
module_version: 1.0.0
readme: README.md
root_url: https://dougzilla32.github.io/CPKAlamofire/api
dash_url: https://dougzilla32.github.io/CPKAlamofire/api/docsets/CPKAlamofire.xml
github_url: https://github.com/dougzilla32/CPKAlamofire
github_file_prefix: https://github.com/dougzilla32/CPKAlamofire/tree/master
